apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstoneproj
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: 237863785462.dkr.ecr.us-east-1.amazonaws.com/capstoneproj:latest
          ports:
            - containerPort: 80